import { Button, Card, CardBody, CardHeader, Col, FormFeedback, FormGroup, Input, Label, Modal, ModalBody, ModalFooter, Row } from "reactstrap"
import { MdOutlineCancel } from "react-icons/md";
import { useEffect, useState } from "react";
const EditUserInfo = ({ formData, handleChange, setUpdatedData, onImageCancel }) => {

    const [modal, setModal] = useState(false);
    const toggle = () => setModal(!modal);

    return (
        <Card className="mb-4">
            <CardHeader>Basic Information</CardHeader>
            <CardBody>
                <Row>
                    <Col md={6}>
                        <FormGroup>
                            <Label>First Name</Label>
                            <Input type="text" name="first_name" value={formData?.first_name} onChange={handleChange} />

                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Last Name</Label>
                            <Input type="text" name="last_name" value={formData?.last_name} onChange={handleChange} />

                        </FormGroup>
                    </Col>
                </Row>
                <Row>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Email</Label>
                            <Input type="email" name="email" value={formData?.email} onChange={handleChange} />

                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Phone</Label>
                            <Input type="text" name="phone" value={formData?.phone} onChange={handleChange} />
                        </FormGroup>
                    </Col>
                </Row>
                <Row>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Username</Label>
                            <Input type="text" name="username" value={formData?.username} onChange={handleChange} />
                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Password</Label>
                            <Input type="password" name="password" disabled={true} />

                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup style={{ cursor: "not-allowed" }}>
                            <Label>Account No</Label>
                            <Input type="text" name="accno" value={formData?.accno} onChange={handleChange} style={{ cursor: "not-allowed" }} />
                            {/*  not allowed to change */}
                            <small className="text-muted">User Not Allowed To Change</small>
                        </FormGroup>
                    </Col>
                </Row>
                <Row>
                    <Col md={6}>
                        <FormGroup >
                            <Label>OTP</Label>
                            <Input type="text" name="otp" value={formData?.otp} style={{ cursor: "not-allowed" }} />
                            {/*  not allowed to change */}
                            <small className="text-muted">User Not Allowed To Change</small>
                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup style={{ cursor: "not-allowed" }}>
                            <Label>Customer Type</Label>
                            <Input type="select" name="cust_type" disabled={true} value={formData?.cust_type?.id} style={{ cursor: "not-allowed" }}>
                                <option value="">Select Type</option>
                                <option value="2">Corporate</option>
                                <option value="1">Retail</option>
                                <option value="3">Franchise</option>
                            </Input>
                            {/*  not allowed to change */}
                            <small className="text-muted">User Not Allowed To Change</small>
                        </FormGroup>
                    </Col>
                </Row>
                <FormGroup style={{ cursor: "not-allowed" }}>
                    <Label>Customer Name</Label>
                    <Input type="text" name="customer_name" disabled value={formData?.customer_name} style={{ cursor: "not-allowed" }} />
                    {/*  not allowed to change */}
                    <small className="text-muted">User Not Allowed To Change</small>
                </FormGroup>

                <Row>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Lead Generated By</Label>
                            <Input type="text" name="referred_by" value={formData?.referred_by} placeholder='Enter Lead Generated By' onChange={handleChange} />
                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Type of Industry</Label>
                            <Input type="text" name="industry" value={formData?.industry}  placeholder='Enter Type of Industry' onChange={handleChange}  />
                        </FormGroup>
                    </Col>
                </Row>
                <Row>
                    <Col md={6}>
                        <FormGroup>
                            <Label>KYC Document </Label>
                            <div className="d-flex align-items-center">
                                {!!formData?.kyc_document ? (
                                    <>
                                        <div className="d-flex align-items-center justify-content-center">
                                            <div>
                                                {typeof formData.kyc_document === 'string' ?
                                                    formData.kyc_document.split("/").pop() :
                                                    formData.kyc_document?.name || "No File Found"
                                                }
                                            </div>
                                            <MdOutlineCancel
                                                onClick={() => {
                                                    setUpdatedData(prev => ({
                                                        ...prev,
                                                        kyc_document: null
                                                    }));
                                                    onImageCancel()
                                                }}
                                                className="text-primary"
                                                style={{
                                                    marginLeft: "17px",
                                                    width: "18px",
                                                    height: "18px",
                                                    cursor: "pointer"
                                                }}
                                            />
                                            <button className="btn text-primary" onClick={toggle}>
                                                View
                                            </button>

                                            {/* Preview image */}
                                            {!!formData?.kyc_document && (
                                                <Modal isOpen={modal} toggle={toggle} fullscreen="xl" size="lg" centered>
                                                    <ModalBody className="d-flex justify-content-center align-content-center">
                                                        {(typeof formData.kyc_document === 'string' || URL.createObjectURL(formData.kyc_document)) ? (
                                                            <img
                                                                className="m-auto"
                                                                style={{ width: "700px", height: "400px" }}
                                                                alt="Document preview"
                                                                src={typeof formData.kyc_document === 'string' ? formData.kyc_document : URL.createObjectURL(formData.kyc_document)}
                                                            />
                                                        ) : (
                                                            <div>File preview not available </div>
                                                        )}
                                                    </ModalBody>
                                                    <ModalFooter>
                                                        <Button color="secondary" onClick={toggle}>
                                                            Cancel
                                                        </Button>
                                                    </ModalFooter>
                                                </Modal>
                                            )}
                                        </div>
                                    </>
                                ) : (
                                    <div className="d-flex">
                                        <Input type="file" name="kyc_document" onChange={handleChange} />
                                    </div>
                                )}

                            </div>


                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup check className="mt-4">
                            <Label check>
                                <Input type="checkbox" name="kyc_approved" checked={formData?.kyc_approved} onChange={handleChange} />
                                KYC Approved
                            </Label>
                        </FormGroup>
                    </Col>
                </Row>
                <Row>
                    <Col md={6}>
                        <FormGroup>
                            <Label>Billing Type </Label>
                            <Input type="text" name="billing_type" value={formData?.billing_type === "null" ? "" : formData?.billing_type} onChange={handleChange} />
                        </FormGroup>
                    </Col>
                </Row>
                <Row>
                    <Col md={6}>
                        <FormGroup>
                            <Label>GST No</Label>
                            <Input type="text" name="gst_no" value={formData?.gst_no === "null" ? "" : formData?.gst_no} onChange={handleChange} />
                        </FormGroup>
                    </Col>
                    <Col md={6}>
                        <FormGroup>
                            <Label>PAN No</Label>
                            <Input type="text" name="pan_no" value={formData?.pan_no === "null" ? "" : formData?.pan_no} onChange={handleChange} />
                        </FormGroup>
                    </Col>
                </Row>

            </CardBody>
        </Card>

    )
}

export default EditUserInfo