const FormDat={
    "first_name":"abcd",
    "last_name": "abc",
    "email": "abc@gmail.com",
    "phone": "4040404040",
    "username": "relay12",
    "accno": "12348", 
    "password":"11221eq",
    "otp": "", 
    "cust_type": 2 ,
    "customer_name": "RELAY EXPRESS PVT LTD111",
    "kyc_document": null, 
    "kyc_approved": false,
    "billing_type": null, 
    "gst_no": null,
    "pan_no": null,
    "addresses": [
   {
     "address": "rajarampuri 8th lane\r\nnear city hospital",
      "city": "Kolhapur",
      "state": "Maharashtra",
      "country": "India",
      "pincode": "416008",
      "landmark": null,
    }
    ],
    "franchise_profile":{
        "postpaid_payment": false,
        "franchise_name": "Onkar",
        "contact_person": "Onkar Madhukar Todkar",
        "address1": "",
        "address2": "rerwerwe",
        "city": "sdadsa",
        "state": "Maharashtra",
        "country": null,
        "landmark": null,
        "pincode": "123231",
        "telephone1": "80806656609",
        "telephone2": null,
        "alt_mobile": null,
        "customer_billing_state": null,
        "branch": null,
        "start_date": "2024-11-16T00:00:00",
        "origin": null,
        "origin_code": null,
        "gst_no": null,
        "pan_no": null,
        "tan_no": null,
        "billing_type": null,
        "credit_days": null,
        "credit_percent": null,
        "unbilled_amount": null,
        "volume_discount": null,
        "contact_origin": null,
        "iec_no": null,
        "bank_ad_code": null,
        "bank_account": null,
        "bank_ifsc": null,
        "lut_no": null,
        "lut_issue_date": null,
        "lut_till_date": null,
        "shipper_type": null,
        "customer_msg": null,
        "account_email": null,
        "geolocation": null,
        "disable_customer_origin": false,
        "email_booking_info": true,
        "sms_booking_info": false,
        "email_forwarding_info": false,
        "email_on_progress": false,
        "email_pod_info": false,
        "sms_pod_info": false,
        "e_invoice": false,
        "whatsapp_booking_info": false,
        "whatsapp_delivery_info": false,
         "velexp_address": null
   }
}